name: cuda_dev
channels:
  - conda-forge
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - backports_abc=0.5
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - certifi=2020.6.20
  - cmake=4.1.2
  - cuda=12.8.1
  - cuda-cccl_linux-64=12.8.90
  - cuda-command-line-tools=12.8.1
  - cuda-compiler=12.8.1
  - cuda-crt-dev_linux-64=12.8.93
  - cuda-crt-tools=12.8.93
  - cuda-cudart=12.8.90
  - cuda-cudart-dev=12.8.90
  - cuda-cudart-dev_linux-64=12.8.90
  - cuda-cudart-static=12.8.90
  - cuda-cudart-static_linux-64=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-cuobjdump=12.8.90
  - cuda-cupti=12.8.90
  - cuda-cupti-dev=12.8.90
  - cuda-cuxxfilt=12.8.90
  - cuda-driver-dev=12.8.90
  - cuda-driver-dev_linux-64=12.8.90
  - cuda-gdb=12.8.90
  - cuda-libraries=12.8.1
  - cuda-libraries-dev=12.8.1
  - cuda-nsight=12.8.90
  - cuda-nvcc=12.8.93
  - cuda-nvcc-dev_linux-64=12.8.93
  - cuda-nvcc-impl=12.8.93
  - cuda-nvcc-tools=12.8.93
  - cuda-nvcc_linux-64=12.8.93
  - cuda-nvdisasm=12.8.90
  - cuda-nvml-dev=12.8.90
  - cuda-nvprof=12.8.90
  - cuda-nvprune=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-nvrtc-dev=12.8.93
  - cuda-nvtx=12.8.90
  - cuda-nvvm-dev_linux-64=12.8.93
  - cuda-nvvm-impl=12.8.93
  - cuda-nvvm-tools=12.8.93
  - cuda-nvvp=12.8.93
  - cuda-opencl=12.8.90
  - cuda-opencl-dev=12.8.90
  - cuda-profiler-api=12.8.90
  - cuda-runtime=12.8.1
  - cuda-sanitizer-api=12.8.93
  - cuda-toolkit=12.8.1
  - cuda-tools=12.8.1
  - cuda-version=12.8
  - cuda-visual-tools=12.8.1
  - cycler=0.10.0
  - dbus=1.16.2
  - expat=2.7.1
  - fmt=11.2.0
  - fontconfig=2.14.1
  - freetype=2.13.3
  - functools32=3.2.3.2
  - futures=3.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gds-tools=1.13.1.3
  - glib=2.84.4
  - glib-tools=2.84.4
  - gmp=6.3.0
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - icu=58.2
  - jpeg=9f
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - kiwisolver=1.1.0
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.8.4.1
  - libcublas-dev=12.8.4.1
  - libcufft=11.3.3.83
  - libcufft-dev=11.3.3.83
  - libcufile=1.13.1.3
  - libcufile-dev=1.13.1.3
  - libcurand=10.3.9.90
  - libcurand-dev=10.3.9.90
  - libcurl=8.17.0
  - libcusolver=11.7.3.90
  - libcusolver-dev=11.7.3.90
  - libcusparse=12.5.8.93
  - libcusparse-dev=12.5.8.93
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.84.4
  - libgomp=15.2.0
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.67.0
  - libnpp=12.3.3.100
  - libnpp-dev=12.3.3.100
  - libnvfatbin=12.8.90
  - libnvfatbin-dev=12.8.90
  - libnvjitlink=12.8.93
  - libnvjitlink-dev=12.8.93
  - libnvjpeg=12.3.5.92
  - libnvjpeg-dev=12.3.5.92
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsanitizer=14.3.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libuv=1.51.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libzlib=1.3.1
  - make=4.4.1
  - matplotlib=2.2.2
  - mpi=1.0
  - ncurses=6.5
  - nlohmann_json=3.11.2
  - nsight-compute=2025.1.1.2
  - nspr=4.37
  - nss=3.117
  - numpy=1.16.5
  - ocl-icd=2.3.2
  - openmpi=4.1.6
  - openssl=3.6.0
  - pcre2=10.46
  - pip=19.3.1
  - pthread-stubs=0.3
  - pyparsing=2.4.7
  - pyqt=5.6.0
  - python=2.7.18
  - python-dateutil=2.8.2
  - pytz=2021.3
  - qt=5.6.3
  - readline=8.3
  - rhash=1.4.6
  - setuptools=44.0.0
  - singledispatch=3.7.0
  - sip=4.18.1
  - six=1.16.0
  - sqlite=3.51.0
  - subprocess32=3.5.4
  - sysroot_linux-64=2.34
  - tk=8.6.15
  - tornado=5.1.1
  - tzdata=2025b
  - wheel=0.37.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
prefix: /home/bryson/miniconda3/envs/cuda_dev
